steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--no-cache',
        '-t',
        'europe-west6-docker.pkg.dev/clever-courier-474119-r9/mn-transcribe/backend:latest',
        './backend'
      ]
images:
  - 'europe-west6-docker.pkg.dev/clever-courier-474119-r9/mn-transcribe/backend:latest'
